### ISSUE TITLE
Dedicated Nodes Table Alignment 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#99]
Tested on Devnet

When the browser is not in full screen the alignment for the table header is broken

![image](https://user-images.githubusercontent.com/101194226/164222778-aec5e68d-1758-440f-86ef-ff5cff842a38.png)

![image](https://user-images.githubusercontent.com/101194226/164222808-937fd8d6-189b-4365-b64c-b88646785c5c.png)

**Comment by mohamedamer453** [comment]
This issue is still available in the dashboard 

![image](https://user-images.githubusercontent.com/101194226/177819832-cad69b2c-111e-4439-a6d3-432e1cfa2379.png)

**Comment by rawdaGastan** [comment]
I think it if fixed now 
![Screenshot from 2022-08-02 11-53-46](https://user-images.githubusercontent.com/47260239/182347015-de123285-a8a1-4c14-8c95-8b7fddd85d28.png)

**Comment by mohamedamer453** [comment]
There is no problem with the title alignment in most cases but at some window sizes the alignment is broken and it keeps changing from one column to the other when you try different window sizes.

![TF DASHBOARD (13)](https://user-images.githubusercontent.com/101194226/183287730-57bef24f-2c7a-4eef-9629-fba24decfeed.gif)

**Comment by khaledyoussef24** [comment]
verified in all sizes
![Screenshot from 2022-08-22 16-48-52](https://user-images.githubusercontent.com/110984055/185951594-5e14db29-278e-47a5-85fc-8bc1865e23eb.png)
![Screenshot from 2022-08-22 16-51-08](https://user-images.githubusercontent.com/110984055/185951612-04087654-3a65-47c1-bd6c-1d4a859d6999.png)
![Screenshot from 2022-08-22 16-51-18](https://user-images.githubusercontent.com/110984055/185951621-1da9ead7-9688-4365-b36d-ec7682c1d13b.png)

**Comment by khaledyoussef24** [comment]
there is still a problem in the alignment of headers
specialy at the price header
![Screenshot from 2022-08-22 16-48-52](https://user-images.githubusercontent.com/110984055/186041161-535ac139-bfda-4eb2-ae56-937b9ec93f10.png)
![Screenshot from 2022-08-22 16-51-08](https://user-images.githubusercontent.com/110984055/186041169-392b77b9-b900-4f2c-8d82-c14b88f9ec05.png)
![Screenshot from 2022-08-22 16-51-18](https://user-images.githubusercontent.com/110984055/186041174-b0468ce9-a5c9-41b4-9868-43aa6b2247fe.png)

**Comment by khaledyoussef24** [comment]
##verified on dev net
steps made to verify

1. go to the dashboard
2. choose the user from the portal
3. choose dedicated notes
4. try to zoom to see the alignment diffrence
![Screenshot from 2022-08-23 13-52-19](https://user-images.githubusercontent.com/110984055/186151448-10f27a63-1fd5-4f3c-8ec4-70ef565fcf4c.png)
![Screenshot from 2022-08-23 13-52-45](https://user-images.githubusercontent.com/110984055/186151452-9b9addbe-1619-48e9-81db-50b19229a9df.png)
